### ISSUE TITLE
[ Suggestion ] Readme.md & screenshots

### ISSUE THREAD

**Issue by PySimpleGUI** [moabdali/MegaCheckers#1]
Use readme.md, a markdown document.  They're super simple to make.  

Also since your program has a GUI, it's important to include screenshots in your readme so that when someone comes to your repo, they immediately see your creation.

Here is some info on adding screenshots:

### To add a screenshot to your readme that will show up on your GitHub's "homepage"

* Open an issue in your project
* Copy and paste an image or drag and drop an image file into the issue text area. There are also upload instructions in the issue.
* GitHub will create something that looks like this in your issue:
```
![SNAG-0767](https://user-images.githubusercontent.com/46163555/80380522-b2c09600-886d-11ea-92cc-e88e14e0917c.jpg)
```
* Copy this above line(s) of text that the Issue created for you
* Edit your readme.md file in your project
* Paste the line of text from the Issue in your readme.md
* The image will now be embedded in your readme and will show up when someone visits your GitHub page
* You'll look like a rock star!

No GUI is too small to show people.  If you've taken the time to post it on GitHub, it's worthy of showing everyone.  Trust me here... people LOVE seeing them.  There are not many GUIs in the Python world and you are a part of the movement that's changing that!

**Comment by moabdali** [comment]
Thank you so much!  Apologies for not responding earlier; I didn't realize you'd commented here.  Again, I owe almost everything to you and your kind words and of course your awesome PySimpleGUI repo.  I will apply your suggestions relatively soonish.  Also, I finally got around to breaking my monolithic file into a few "friendlier" files that are each under 4000 lines long.  Hopefully now people will offer actual comments about the game instead of just saying "wow it's too long, bye" haha.

**Comment by moabdali** [comment]
And it is done!  Thank you so much for your input.  I guess this is technically my first official "solved GitHub issue".
